### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by nickhristov** [msink/kotlin-libui#6]
```
➜  kotlin-libui git:(master) ./gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :libui:compileKonanLibuiLinux_x64 FAILED
Exception in thread "main" java.lang.Error: /tmp/tmp4030171382076881273.c:1:10: fatal error: 'ui.h' file not found
        at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:145)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:916)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:906)
        at org.jetbrains.kotlin.native.interop.indexer.NativeIndexKt.buildNativeIndex(NativeIndex.kt:56)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:242)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:36)
        at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:88)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:18)

FAILURE: Build failed with an exception.
```

Looks like I am missing a library?

**Comment by msink** [comment]
Please run `build.sh`, or follow instructions in #5

**Comment by nickhristov** [comment]
Ok, got past that part, I think. Now dies here:

```
./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/media/nhh/Development/kotlin-libui/libui-ktx/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':libui-ktx'.
> Extension with name 'konanArtifacts' does not exist. Currently registered extension names: [ext]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

Also, btw:
```
➜  kotlin-libui git:(master) ✗ cd libui
➜  libui git:(master) ✗ tree
.
├── build
│   └── out
│       └── libui.a
└── src
    ├── ui.h
    └── ui_unix.h

3 directories, 3 files
```

**Comment by msink** [comment]
I do not know, sorry.
In fact I didnt build Linux and Mac versions locally, but on Travis CI it worked.

**Comment by msink** [comment]
Works on my linux image (Ubuntu 16.04):

- Download https://github.com/andlabs/libui/releases/download/alpha4.1/libui-alpha4.1-linux-amd64-static.tgz
- Unpack, move `ui.h` to `libui/src`, `libui.a` to `libui/build/our/
- `./gradlew build`

BUILD SUCCESSFUL in 4m 59s

**Comment by msink** [comment]
I removed building libui.a from sources, so now build  does not depend on host toolchain and cmake.

Does it work now?

**Comment by apahl** [comment]
Hi, thanks for this very promising wrapper.

I get the following error when building (I think it is related, therefore I am not opening a new issue):
```
$ ../gradlew build

> Task :libui:compileKonanLibuiLinux_x64 FAILED
Exception in thread "main" java.lang.IllegalStateException: Could not find 'libui.a' binary in neither of [libui/build]
        at org.jetbrains.kotlin.native.interop.gen.LibraryUtilsKt.resolveLibraries(LibraryUtils.kt:31)
        at org.jetbrains.kotlin.native.interop.gen.LibraryUtilsKt.argsToCompiler(LibraryUtils.kt:40)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:296)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:36)
        at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:88)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:18)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libui:compileKonanLibuiLinux_x64'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
4 actionable tasks: 2 executed, 2 up-to-date
```

directory structure (`libui.a` seems to be in the correct location):
```
$ tree
.
├── build
│   ├── konan
│   │   └── libs
│   │       └── linux_x64
│   │           └── libui.klib-build
│   │               ├── kotlin
│   │               │   └── libui
│   │               │       └── libui.kt
│   │               ├── manifest.properties
│   │               └── natives
│   │                   └── cstubs.bc
│   ├── libui.a
│   ├── libui-alpha4.1.tgz
│   ├── ui.h
│   └── ui_unix.h
├── build.gradle
└── libui.def
```

Kind regards,  
Axel

**Comment by msink** [comment]
Well, quick fix:
``` diff
--- a/libui/libui.def
+++ b/libui/libui.def
@@ -3,7 +3,7 @@ headers = ui.h
 noStringConversion = uiFreeInitError
 
 staticLibraries = libui.a
-libraryPaths = libui/build
+libraryPaths = build libui/build
 
 linkerOpts.osx = -lobjc -framework Foundation -framework AppKit
 
```

In general it should be absolute patch, but for now I do not know how to make it absolute.

**Comment by apahl** [comment]
Indeed, that fixed the issue for me.

Thanks a lot.

Kind regards,  
Axel
